apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
      - name: todoapp
        image: kartiksharmacs16/flask-docker-app:$BUILD_ID
        ports:
        - containerPort: 5000
        volumeMounts:
          - name: todo-volume
            mountPath: /var/lib
      volumes:
        - name: todo-volume
          persistentVolumeClaim:
            claimName: todo-claim
---
apiVersion: v1
kind: Service
metadata:
  name: todo-service
spec:
  selector:
    app: todoapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: todo-ingress
  labels:
    name: todo-ingress
spec:
  rules:
  - host: kartiktodoapp.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: todo-service
            port: 
              number: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: todo-peristent-volume
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
